[package]
name = "bevy_loading"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/inodentry/bevy_loading"
keywords = ["game", "gamedev", "bevy"]
categories = ["game-engines"]
description = "Bevy plugin to help implement loading states"

[dependencies]
bevy = { version = "0.6.0", default-features = false }

[dev-dependencies]
bevy = "0.6.0"
